<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>vpr</string>
	</array>
	<key>name</key>
	<string>Viper</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?&lt;=^)(\s)*(import )</string>
			<key>end</key>
			<string>([^a-zA-Z0-9\.\_\-\s]|$)</string>
			<key>name</key>
			<string>keyword.control.viper</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([a-zA-Z0-9\.\_\-\s])</string>
					<key>name</key>
					<string>string.quoted.double.viper</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>((\b(not|and|or|is|onto)\b)|\+|\-|\/|\*|\^|\&gt;\=|\&lt;\=|\&gt;|\&lt;|\:|\.)</string>
			<key>name</key>
			<string>support.function.viper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\bglobal\b)</string>
			<key>name</key>
			<string>storage.modifier.viper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(new|for|in|to|if|else|while|return|continue|break|step)\b)</string>
			<key>name</key>
			<string>keyword.control.viper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\\\s*)(?=$|\'(?:[^'\\]|\\.)*\'\s*$)</string>
			<key>name</key>
			<string>keyword.control.viper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((\b|\-)[0-9]+(\.[0-9]+)?\b)</string>
			<key>name</key>
			<string>constant.numeric.viper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(true|false)\b)</string>
			<key>name</key>
			<string>constant.language.viper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\bthis\b)</string>
			<key>name</key>
			<string>constant.language.viper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[)|(\])</string>
			<key>name</key>
			<string>constant.language.viper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((\()|(\)))</string>
			<key>name</key>
			<string>constant.language.viper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b([A-Za-z][A-Za-z0-9]*)(\s*)\!)</string>
			<key>name</key>
			<string>entity.name.function.viper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((?&lt;=^|global|\.)\s*([A-Za-z][A-Za-z0-9]*)(?=[^=.]*\=\s*$))</string>
			<key>name</key>
			<string>entity.name.function.viper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b([A-Za-z][A-Za-z0-9]*)(?!((\s*)\!))\b)</string>
			<key>name</key>
			<string>entity.name.viper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((?&lt;!\&lt;)(?&lt;!\&gt;)\=)</string>
			<key>name</key>
			<string>keyword.operator.assignment.viper</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\'</string>
			<key>end</key>
			<string>\'</string>
			<key>name</key>
			<string>comment.block.viper</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?:[^'\\]|\\.)</string>
					<key>name</key>
					<string>comment.character.viper</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>(\"|$)</string>
			<key>name</key>
			<string>string.quoted.double.viper</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?:[^"\\]|\\.)</string>
					<key>name</key>
					<string>string.quoted.character.viper</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.viper</string>
	<key>uuid</key>
	<string>c4529047-160a-40ca-a754-2aa31bf12c9a</string>
</dict>
</plist>
